---

galaxy_info:
  author: 'Bj√∏rn-Vegar Borge'
  description: 'Palo Alto Networks firewall provisioning'
  company: 'Netsecurity'

  license: 'GLWTPL'

  min_ansible_version: '2.1'

  platforms:
    - name: 'PAN-OS'
      versions:
        - 'all'

  galaxy_tags:
    - 'paloaltonetworks'
    - 'security'

dependencies: []
# - role: pan_management_profiles
# - role: pan_tags
# - role: pan_zones
